name: Meyl
options:
  bundleIdPrefix: com.antitic
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
settings:
  base:
    SWIFT_VERSION: "5.0"
    MARKETING_VERSION: "1.0.1"
    CURRENT_PROJECT_VERSION: "1"
targets:
  Meyl:
    type: application
    platform: iOS
    sources:
      - path: Meyl
    info:
      path: Meyl/Info.plist
      properties:
        CFBundleDisplayName: Meyl
        CFBundleShortVersionString: $(MARKETING_VERSION)
        CFBundleVersion: $(CURRENT_PROJECT_VERSION)
        UILaunchScreen:
          UIColorName: LaunchBackground
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
        UIUserInterfaceStyle: Dark
        UIStatusBarStyle: UIStatusBarStyleLightContent
        NSAppTransportSecurity:
          NSAllowsArbitraryLoads: true
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: com.antitic.meyl
        PRODUCT_NAME: Meyl
        TARGETED_DEVICE_FAMILY: "1"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        CODE_SIGN_STYLE: Automatic
        ENABLE_PREVIEWS: YES
schemes:
  Meyl:
    build:
      targets:
        Meyl: all
    run:
      config: Debug
    archive:
      config: Release
